version: "3.7"
services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: node_app
    image: node-docker:v1
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - node-docker
volumes:
  node_modules: {}
  app:
    driver: local
    driver_opts:
      type: bind
      device: ${PWD}/src/
networks:
  node-docker:
    name: node-docker
    driver: bridge
