FROM node:iron-alpine
# Create app directory
WORKDIR /app

RUN npm i -g nodemon

EXPOSE 3000 9229

COPY src/package* ./

RUN npm install

COPY src/ ./

# Add debug script to package.json to start app in debug mode
CMD [ "npm", "run", "debug" ]
